/** @format */

import styles from './layout.module.css';
import { Inter } from 'next/font/google';
import Navbar from '../components/navbar';
import Footer from '../components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={[inter.className, styles.container].join(' ')}>
				<Navbar />
				<div className={styles.children}>{children}</div>
				<Footer />
			</body>
		</html>
	);
}
